// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteModel(arg1) {
    return window['go']['main']['App']['DeleteModel'](arg1);
}

export function GetConfig(arg1) {
    return window['go']['main']['App']['GetConfig'](arg1);
}

export function GetDashboardStats() {
    return window['go']['main']['App']['GetDashboardStats']();
}

export function GetModels() {
    return window['go']['main']['App']['GetModels']();
}

export function GetProxyStatus() {
    return window['go']['main']['App']['GetProxyStatus']();
}

export function Greet(arg1) {
    return window['go']['main']['App']['Greet'](arg1);
}

export function SaveModel(arg1) {
    return window['go']['main']['App']['SaveModel'](arg1);
}

export function SendChat(arg1) {
    return window['go']['main']['App']['SendChat'](arg1);
}

export function SetConfig(arg1, arg2) {
    return window['go']['main']['App']['SetConfig'](arg1, arg2);
}

export function StartProxy(arg1) {
    return window['go']['main']['App']['StartProxy'](arg1);
}

export function StopProxy() {
    return window['go']['main']['App']['StopProxy']();
}

export function TestModel(arg1) {
    return window['go']['main']['App']['TestModel'](arg1);
}
