// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteModel(arg1: string): Promise<void>;
export function GetConfig(arg1: string): Promise<string>;
export function GetDashboardStats(): Promise<types.DashboardStats>;
export function GetModels(): Promise<types.Model[]>;
export function GetProxyStatus(): Promise<types.ProxyStatus>;
export function Greet(arg1: string): Promise<string>;
export function SaveModel(arg1: types.Model): Promise<void>;
export function SendChat(arg1: types.ChatRequest): Promise<void>;
export function SetConfig(arg1: string, arg2: string): Promise<void>;
export function StartProxy(arg1: number): Promise<void>;
export function StopProxy(): Promise<void>;
export function TestModel(arg1: types.Model): Promise<string>;
