// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteModel(arg1:string):Promise<void>;

export function GetConfig(arg1:string):Promise<string>;

export function GetDashboardStats():Promise<Record<string, any>>;

export function GetModels():Promise<Array<main.ModelJSON>>;

export function GetProxyStatus():Promise<Record<string, any>>;

export function SaveModel(arg1:main.ModelJSON):Promise<void>;

export function SendChat(arg1:main.ChatRequest):Promise<main.ChatResponse>;

export function SetConfig(arg1:string,arg2:string):Promise<string>;

export function StartProxy(arg1:number):Promise<string>;

export function StopProxy():Promise<string>;

export function TestModel(arg1:main.ModelJSON):Promise<string>;
