// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyAgentConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyAgentConfig'](arg1, arg2, arg3);
}

export function DeleteModel(arg1) {
  return window['go']['main']['App']['DeleteModel'](arg1);
}

export function ExportModels(arg1) {
  return window['go']['main']['App']['ExportModels'](arg1);
}

export function GetActiveModels() {
  return window['go']['main']['App']['GetActiveModels']();
}

export function GetAutoStart() {
  return window['go']['main']['App']['GetAutoStart']();
}

export function GetClassifierConfig() {
  return window['go']['main']['App']['GetClassifierConfig']();
}

export function GetConfig(arg1) {
  return window['go']['main']['App']['GetConfig'](arg1);
}

export function GetDashboardLogs(arg1, arg2) {
  return window['go']['main']['App']['GetDashboardLogs'](arg1, arg2);
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetDefaultClassifierConfig() {
  return window['go']['main']['App']['GetDefaultClassifierConfig']();
}

export function GetModels() {
  return window['go']['main']['App']['GetModels']();
}

export function GetProxyMode() {
  return window['go']['main']['App']['GetProxyMode']();
}

export function GetProxyStatus() {
  return window['go']['main']['App']['GetProxyStatus']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function ImportModels(arg1, arg2) {
  return window['go']['main']['App']['ImportModels'](arg1, arg2);
}

export function IsWindowMaximized() {
  return window['go']['main']['App']['IsWindowMaximized']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function PreviewAgentConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['PreviewAgentConfig'](arg1, arg2, arg3);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ReadImportFile() {
  return window['go']['main']['App']['ReadImportFile']();
}

export function SaveExportFile(arg1) {
  return window['go']['main']['App']['SaveExportFile'](arg1);
}

export function SaveModel(arg1) {
  return window['go']['main']['App']['SaveModel'](arg1);
}

export function SendChat(arg1) {
  return window['go']['main']['App']['SendChat'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetClassifierConfig(arg1) {
  return window['go']['main']['App']['SetClassifierConfig'](arg1);
}

export function SetConfig(arg1, arg2) {
  return window['go']['main']['App']['SetConfig'](arg1, arg2);
}

export function SetProxyMode(arg1) {
  return window['go']['main']['App']['SetProxyMode'](arg1);
}

export function StartProxy(arg1) {
  return window['go']['main']['App']['StartProxy'](arg1);
}

export function StartWindowDrag() {
  return window['go']['main']['App']['StartWindowDrag']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function TestModel(arg1) {
  return window['go']['main']['App']['TestModel'](arg1);
}

export function ToggleMaximizeWindow() {
  return window['go']['main']['App']['ToggleMaximizeWindow']();
}
