// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function DeleteModel(arg1:string):Promise<void>;

export function GetAutoStart():Promise<boolean>;

export function GetConfig(arg1:string):Promise<string>;

export function GetDashboardStats():Promise<Record<string, any>>;

export function GetModels():Promise<Array<core.ModelJSON>>;

export function GetProxyStatus():Promise<Record<string, any>>;

export function HideWindow():Promise<void>;

export function IsWindowMaximized():Promise<boolean>;

export function MinimizeWindow():Promise<void>;

export function QuitApp():Promise<void>;

export function SaveModel(arg1:core.ModelJSON):Promise<void>;

export function SendChat(arg1:core.ChatRequest):Promise<core.ChatResponse>;

export function SetAutoStart(arg1:boolean):Promise<string>;

export function SetConfig(arg1:string,arg2:string):Promise<string>;

export function StartProxy(arg1:number):Promise<string>;

export function StartWindowDrag():Promise<void>;

export function StopProxy():Promise<string>;

export function TestModel(arg1:core.ModelJSON):Promise<string>;

export function ToggleMaximizeWindow():Promise<boolean>;
