// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export namespace types {
    export interface ChatRequest {
        messages: ChatMessage[];
        mode: string;
        modelId: string;
    }

    export interface ChatMessage {
        role: string;
        content: string;
    }

    export interface Model {
        id: string;
        name: string;
        provider: string;
        baseUrl: string;
        apiKey: string;
        modelId: string;
        reasoning: number;
        coding: number;
        creativity: number;
        speed: number;
        costEfficiency: number;
        maxRpm: number;
        maxTpm: number;
        isActive: boolean;
    }

    export interface DashboardStats {
        todayRequests: number;
        todayTokens: number;
        avgLatency: number;
        modelUsage: ModelUsage[];
        complexityDistribution: ComplexityDistribution;
        recentLogs: LogEntry[];
    }

    export interface ModelUsage {
        modelName: string;
        count: number;
        percentage: number;
    }

    export interface ComplexityDistribution {
        simple: number;
        medium: number;
        complex: number;
    }

    export interface LogEntry {
        time: string;
        model: string;
        complexity: string;
        source: string;
        tokens: number;
        latency: number;
    }

    export interface ProxyStatus {
        running: boolean;
        port: number;
        url: string;
    }
}
